focus:
  enabled: true
  modules:
    - ":modules:one"
replace:
  enabled: false
  modules:
      #  but don't forget to register stub via kotusIncludeWithStub
      - ":modules:three"
      - ":modules:three": ":modules:three-stub"
